# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sungjae Lee
title: Software Engineer at NAVER Corp.
email: sungjae.lee@yonsei.ac.kr
# email_title: Email (Email title override)
website: llsj14.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  llsj14
stackoverflow_username: jaylee
linkedin_username: sungjae-lee-9413b0180

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer at NAVER Corp.
  I'm interested in machine learning, workload characterization, and computer architectures.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: NAVER Corp.
        sub_title: Software Engineer
        caption: 2020.12 - present
        link: www.navercorp.com

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Yonsei University
        sub_title: M.S. in School of Electrical and Electronic Engineering
        caption: 2019.03 - 2021.02
        description: >
          Advisor : William J. Song
          Lab : Intelligent Computing System Lab (ICSL)
      - layout: top-left
        title: Yonsei University
        sub_title: B.S. in School of Electrical and Electronic Engineering
        caption: 2013.03 - 2019.02
        
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nebula
        link: https://github.com/yonsei-icsl/nebula
        description: | # this will include new lines to allow paragraphs
          Lightweight Neural Network Benchmarks

  - title: Publications
    layout: text
    content: |
      **S. Lee**, "Exploiting Large and Small Page Sizes in Two-Tiered Memory System.," Master's Thesis, Dec. 2020. |
      B. Kim, **S. Lee**, A. Trivedi, and W. Song, "Energy-Efficient Acceleration of Deep Neural Networks on Realtime-Constrained Embedded Edge Devices," IEEE Access, vol. 8, Nov. 2020, pp. 216259-216270. |
      B. Kim, **S. Lee**, C. Park, H. Kim, and W. Song, "The Nebula Benchmark Suite: Implications of Lightweight Neural Networks," IEEE Transactions on Computers, Oct. 2020. |
      B. Kim, **S. Lee**, and W. Song, "Nebula: Lightweight Neural Network Benchmarks," Workshop on Modeling and Simulation of Systems and Applications, Aug. 2020.
  
  - title: Scholarships and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      Honors Student Award (Yonsei University, Mar. 2013 / Sep. 2017) |
      4th Place Award (Korea Auto-Vehicle Safety Association (KASA), Autonomous Car Racing in 2017 International Student Car Competition)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
