# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sungjae Lee
title: Software Engineer at NAVER Corp.
email: sungjae.lee@yonsei.ac.kr
# email_title: Email (Email title override)
website: llsj14.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  llsj14
stackoverflow_username: "9215366"
linkedin_username: sungjae-lee-9413b0180

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/leesungjae.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer at NAVER Corp.
  I'm interested in machine learning and backend engineering.
  
  Programming Languages : C/C++, CUDA C/C++, Python
  
  Simulation Tools : gem5, MARSSx86, DRAMsim3
  
  Backend Development : Kubernetes, Linux

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NAVER Corp.
        sub_title: Software Engineer
        caption: 2020.12 - present
        link: www.navercorp.com

  - title: Education
    layout: list
    content:
      - layout: left
        title: Yonsei University
        caption: 2019.03 - 2021.02
        description: M.S. in School of Electrical and Electronic Engineering
      - layout: left
        title: Yonsei University
        caption: 2013.03 - 2019.02
        description: B.S. in School of Electrical and Electronic Engineering
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nebula
        sub_title: Lightweight Neural Network Benchmarks
        link: https://github.com/yonsei-icsl/nebula   
  - title: Presentations
    layout: text
    content:
        Hyper scale AI, ‘HyperCLOVA’ serving (DEVIEW 2021)
  - title: Publications
    layout: text
    content: |
      S. Hong, S. Moon, J. Kim, **S. Lee**, M. Kim, D. Lee, and J. Kim, "DFX: A Low-latency Multi-FPGA Appliance for Accelerating Transformer-based Text Generation," IEEE/ACM International Symposium on Microarchitecture (MICRO), Oct. 2022.
    
      S. Hong, S. Moon, J. Kim, **S. Lee**, M. Kim, D. Lee, and J. Kim, "DFX: A Low-latency Multi-FPGA Appliance for Accelerating Transformer-based Text Generation," Symposium on High Performance Chips (HotChips), Aug. 2022.
      
      B. Kim, H. Kim, S. Lee, G. Lee, D. Kwak, D. H. Jeon, S. Park, S. Kim, S. Kim, D. Seo, H. Lee, M. Jeong, **S. Lee**, M. Kim, S. H. Ko, S. Kim, T. Park, J. Kim, S. Kang, N. Ryu, K. M. Yoo, M. Chang, S. Suh, S. In, J. Park, K. Kim, H. Kim, J. Jeong, Y. G. Yeo, D. Ham, D. Park, M. Y. Lee, J. Kang, I. Kang, J. Ha, W. Park, N. Sung, "What Changes Can Large-scale Language Models Bring? Intensive Study on HyperCLOVA: Billions-scale Korean Generative Pretrained Transformers", Conference on Empirical Methods in Natural Language Processing (EMNLP), Nov. 2021.
      
      **S. Lee**, "Exploiting Large and Small Page Sizes in Two-Tiered Memory System," Master's Thesis, School of Electrical and Electronic Engineering, Yonsei University, Dec. 2020.
      
      B. Kim, **S. Lee**, A. Trivedi, and W. Song, "Energy-Efficient Acceleration of Deep Neural Networks on Realtime-Constrained Embedded Edge Devices," IEEE Access, Nov. 2020.
      
      B. Kim, **S. Lee**, C. Park, H. Kim, and W. Song, "The Nebula Benchmark Suite: Implications of Lightweight Neural Networks," IEEE Transactions on Computers, Oct. 2020.
      
      B. Kim, **S. Lee**, and W. Song, "Nebula: Lightweight Neural Network Benchmarks," Workshop on Modeling and Simulation of Systems and Applications, Aug. 2020.
  - title: Patents
    layout: text
    content: |
      W. Song, B. Kim, and **S. Lee**, “Operation Device of Artificial Neural Network, Operation Method of Artificial Neural Network and Computer Program Stored in A Recording Medium to Execute The Method,” 10-2021-0071874, June 2021.
  - title: Scholarships and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      Scholarship for combined BS/MS program (Yonsei University, Full tuition for master course, Mar. 2019 - June 2020)
    
      4th Place Award (Korea Auto-Vehicle Safety Association (KASA), Autonomous Car Racing in 2017 International Student Car Competition)
      
      Honors Student Award (Yonsei University, Mar. 2013 / Sep. 2017)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
